/**
 * Generates supabase/seed.sql — DEMO DATA FOR DEVELOPMENT / TEST ENVIRONMENTS ONLY.
 *
 *   npx tsx scripts/generate-seed.ts      (re-generate after changing demo content)
 *   npm run db:seed                       (loads seed.sql into DATABASE_URL)
 *
 * Every demo record has a fixed id, so running the seed twice is harmless.
 * Demo passwords are public knowledge — NEVER load this into production.
 */
import { config } from "dotenv";
import { writeFileSync } from "node:fs";
import { hash } from "@node-rs/argon2";
import { validateBlock, type BlockType } from "../lib/blocks/registry";
import { seededShuffle, shuffleAwayFrom } from "../lib/content/shuffle";

config({ path: ".env.local" });
const DEMO_PASSWORD = process.env.SEED_DEMO_PASSWORD || "Gravitas@2026";

let n = 0;
const ids = new Map<string, string>();
/** Stable UUID per name. */
const id = (name: string) => {
  if (!ids.has(name)) ids.set(name, `00000000-0000-4000-8000-${(++n).toString(16).padStart(12, "0")}`);
  return ids.get(name)!;
};
const q = (v: unknown): string =>
  v === null || v === undefined ? "null" : typeof v === "number" || typeof v === "boolean" ? String(v) : `'${String(v).replace(/'/g, "''")}'`;
const j = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;

const out: string[] = [
  "-- GENERATED by scripts/generate-seed.ts — demo data for dev/test ONLY. Do not load into production.",
  "begin;",
];

type B = { type: BlockType; content: any; answerKey?: any; settings?: any };

async function main() {
  const pw = await hash(DEMO_PASSWORD, { memoryCost: 19456, timeCost: 2, parallelism: 1, algorithm: 2 });

  // ── School ───────────────────────────────────────────────────────────────
  out.push(`insert into app.schools (id, name, code, city, district, board, contact_name) values
    (${q(id("school"))}, 'Gravitas Demo School', 'DEMO01', 'Gadag', 'Gadag', 'Karnataka State Board', 'Demo Coordinator')
    on conflict (id) do nothing;`);

  // ── Staff (one per role) and an adult learner ────────────────────────────
  const staff: [string, string, string, string, { program?: string; school?: boolean }?][] = [
    ["superadmin", "Super", "Admin", "super_admin"],
    ["pm", "Priya", "Manager", "program_manager", { program: "aiq" }],
    ["author", "Arjun", "Author", "content_author", { program: "aiq" }],
    ["reviewer", "Rekha", "Reviewer", "content_reviewer", { program: "aiq" }],
    ["blogwriter", "Bharat", "Writer", "blog_writer"],
    ["blogeditor", "Bhavana", "Editor", "blog_editor"],
    ["trainer", "Tara", "Trainer", "trainer", { school: true }],
    ["judge", "Jagadish", "Judge", "judge"],
    ["coordinator", "Kavya", "Coordinator", "school_coordinator", { school: true }],
    ["finance", "Farhan", "Finance", "finance"],
  ];
  for (const [key, first, last] of staff) {
    out.push(`insert into app.users (id, login_kind, email, password_hash, first_name, last_name, email_verified_at)
      values (${q(id("u:" + key))}, 'email', ${q(`${key}@gravitas.test`)}, ${q(pw)}, ${q(first)}, ${q(last)}, now()) on conflict (id) do nothing;`);
  }
  out.push(`insert into app.users (id, login_kind, email, password_hash, first_name, last_name, email_verified_at)
    values (${q(id("u:learner"))}, 'email', 'learner@gravitas.test', ${q(pw)}, 'Anil', 'Learner', now()) on conflict (id) do nothing;`);

  // ── School learners (minors): school code + username + 6-digit PIN ───────
  const kids: [string, string, string, string, string][] = [
    ["aarav.k", "Aarav", "K", "482913", "9"],
    ["diya.s", "Diya", "S", "615204", "10"],
  ];
  for (const [username, first, last, pin, cls] of kids) {
    const pinHash = await hash(pin, { memoryCost: 19456, timeCost: 2, parallelism: 1, algorithm: 2 });
    out.push(`insert into app.users (id, login_kind, password_hash, first_name, last_name)
      values (${q(id("u:" + username))}, 'school_pin', ${q(pinHash)}, ${q(first)}, ${q(last)}) on conflict (id) do nothing;`);
    out.push(`insert into app.school_learners (user_id, school_id, username, class, section, pin_set_at)
      values (${q(id("u:" + username))}, ${q(id("school"))}, ${q(username)}, ${q(cls)}, 'A', now()) on conflict (user_id) do nothing;`);
  }

  // ── Programs ─────────────────────────────────────────────────────────────
  out.push(`insert into app.programs (id, slug, name, tagline, description, audience, visibility, pass_mark, unlock_rule, marketing, created_by) values
    (${q(id("aiq"))}, 'ai-explorer-quest', 'AI Explorer Quest', 'Five levels. One AI adventure.',
     'A hands-on AI adventure for Classes 8–12 and PUC, delivered in your school computer lab, ending with a Grand Finale at Gravitas Campus.',
     'school', 'public', 50, 'sequential', ${j({ duration: "5 levels · 1 season", outcomes: ["Understand what AI is and is not", "Write clear prompts using Role-Task-Context-Format", "Use AI tools safely and responsibly"] })}, ${q(id("u:superadmin"))}),
    (${q(id("py"))}, 'python-professional', 'Python Professional', 'Job-ready Python from zero.',
     'A job-oriented Python program for graduates and professionals: fundamentals, problem solving, and real projects.',
     'adult', 'public', 60, 'sequential', ${j({ duration: "12 weeks", outcomes: ["Write clean Python programs", "Solve problems with data structures", "Build portfolio projects"] })}, ${q(id("u:superadmin"))})
    on conflict (id) do nothing;`);

  // Role assignments (scoped where relevant)
  for (const [key, , , role, scope] of staff) {
    out.push(`insert into app.role_assignments (id, user_id, role_id, program_id, school_id)
      select ${q(id("ra:" + key))}, ${q(id("u:" + key))}, r.id, ${scope?.program ? q(id(scope.program)) : "null"}, ${scope?.school ? q(id("school")) : "null"}
        from app.roles r where r.key = ${q(role)} on conflict do nothing;`);
  }
  // Program manager also manages Python (shows multi-program scoping)
  out.push(`insert into app.role_assignments (id, user_id, role_id, program_id)
    select ${q(id("ra:pm-py"))}, ${q(id("u:pm"))}, r.id, ${q(id("py"))} from app.roles r where r.key = 'program_manager' on conflict do nothing;`);

  // ── AI Explorer Quest: 5 levels ──────────────────────────────────────────
  const aiqLevels = ["Spark Rookie", "Prompt Ninja", "Pixel Wizard", "Bot Commander", "Vibe Legend"];
  aiqLevels.forEach((name, i) => {
    out.push(`insert into app.levels (id, program_id, position, name, slug, description, badge_name) values
      (${q(id("aiq:l" + i))}, ${q(id("aiq"))}, ${i}, ${q(name)}, ${q(name.toLowerCase().replace(/\s+/g, "-"))},
       ${q(["Discover what AI is and meet your first AI tools.", "Master the art of the prompt.", "Create images and visuals with AI.", "Build your own chatbot.", "Ship a creative AI project."][i])}, ${q(name)})
      on conflict (id) do nothing;`);
  });
  out.push(`insert into app.modules (id, level_id, position, title, description) values
    (${q(id("aiq:m0"))}, ${q(id("aiq:l0"))}, 0, 'Meet AI', 'What AI is, where we see it, and how to talk to it.') on conflict (id) do nothing;`);

  const lesson1: B[] = [
    { type: "heading", content: { text: "Welcome, Spark Rookie! ⚡", level: 2 } },
    { type: "rich_text", content: { markdown: "**Artificial Intelligence (AI)** is when computers learn *patterns* from lots of examples, so they can make predictions or create new things.\n\nYou already use AI every day:\n- 🎵 Music apps suggesting songs\n- 🗺️ Maps finding the fastest route\n- 📷 Phone cameras recognising faces" } },
    { type: "callout", content: { variant: "tip", title: "Think of it like this", markdown: "AI is like a student who has read millions of books — very fast, but it can still make mistakes!" } },
    { type: "image", content: { src: "/seed/robot.svg", alt: "A friendly blue cartoon robot with an orange antenna", caption: "AI is a tool — you are the explorer in charge." } },
    { type: "video", content: { url: "https://www.youtube.com/watch?v=a0_lo_GDcFw", title: "What is Artificial Intelligence? (sample video — replace with your own)" } },
    { type: "key_terms", content: { title: "Key terms", terms: [
      { term: "Artificial Intelligence", definition: "Computer systems that learn from data to make predictions or create content.", link: "" },
      { term: "Data", definition: "Examples (text, pictures, numbers) that an AI learns from.", link: "" },
      { term: "Prompt", definition: "The instruction you give to an AI tool.", link: "" },
    ] } },
    { type: "flashcards", content: { cards: [
      { front: "What does AI stand for?", back: "Artificial Intelligence" },
      { front: "What does an AI learn from?", back: "Data — lots of examples" },
      { front: "Is AI always right?", back: "No! Always check important facts." },
    ] } },
    { type: "mcq", content: { question: "Which of these uses AI?", multiple: false, options: [{ id: "a", text: "A light switch" }, { id: "b", text: "A music app suggesting songs" }, { id: "c", text: "A pencil" }] },
      answerKey: { correct: ["b"], explanation: "Music apps learn from what you listen to and predict what you'll like next.", optionFeedback: { a: "A switch just turns on or off — no learning involved." } } },
    { type: "mcq", content: { question: "Select ALL the things AI can do.", multiple: true, options: [{ id: "a", text: "Recognise faces in photos" }, { id: "b", text: "Suggest the fastest route" }, { id: "c", text: "Feel emotions like humans" }, { id: "d", text: "Translate languages" }] },
      answerKey: { correct: ["a", "b", "d"], explanation: "AI can recognise, predict and translate — but it does not have feelings." } },
    { type: "fill_blank", content: { text: "AI stands for Artificial [[1]]. It learns patterns from [[2]]." },
      answerKey: { blanks: { "1": ["intelligence"], "2": ["data", "examples"] }, explanation: "AI = Artificial Intelligence, and it learns from data." } },
    { type: "sort", content: { prompt: "Put the steps of how an AI learns in order.", items: [{ id: "s1", text: "Collect lots of examples (data)" }, { id: "s2", text: "Find patterns in the data" }, { id: "s3", text: "Make a prediction" }, { id: "s4", text: "Check and improve" }] },
      answerKey: { order: ["s1", "s2", "s3", "s4"], explanation: "Data → patterns → prediction → improvement." } },
    { type: "match", content: { prompt: "Match each AI tool to what it does.", left: [{ id: "l1", text: "Maps app" }, { id: "l2", text: "Translator" }, { id: "l3", text: "Photo app" }], right: [{ id: "r1", text: "Finds the fastest route" }, { id: "r2", text: "Changes Kannada to English" }, { id: "r3", text: "Groups photos by face" }] },
      answerKey: { pairs: { l1: "r1", l2: "r2", l3: "r3" }, explanation: "Each tool uses AI for a different job." } },
    { type: "walkthrough", content: { steps: [
      { title: "Spot it", markdown: "Look around your home for one device that uses AI.", image: "" },
      { title: "Name it", markdown: "Write down what it predicts or creates.", image: "" },
      { title: "Share it", markdown: "Tell your trainer in the next lab session!", image: "" },
    ] } },
    { type: "file", content: { url: "/seed/spark-rookie-cheatsheet.txt", fileName: "Spark Rookie cheat sheet", description: "A one-page summary to keep." } },
  ];
  const lesson2: B[] = [
    { type: "callout", content: { variant: "remember", title: "Golden rule", markdown: "Never type personal information (phone number, address, passwords) into any AI tool." } },
    { type: "rich_text", content: { markdown: "A great prompt has **four parts**:\n\n1. **Role** — who should the AI act as?\n2. **Task** — what exactly should it do?\n3. **Context** — what background does it need?\n4. **Format** — how should the answer look?" } },
    { type: "short_answer", content: { question: "In one word: what do we call the instruction we give to an AI?", placeholder: "Type one word", minWords: 1 }, answerKey: { acceptable: ["prompt", "a prompt"], explanation: "It's called a prompt." } },
    { type: "prompt_builder", content: {
      instructions: "Build a prompt that asks an AI to help you prepare for a science quiz.",
      scenario: "You have a Class 9 science quiz on 'Light and reflection' next week.",
      hints: { role: "e.g. You are a friendly science teacher…", task: "e.g. Create 5 practice questions…", context: "e.g. I am in Class 9, studying reflection…", format: "e.g. A numbered list with answers at the end" },
      minWordsPerField: 3,
      checklist: [{ id: "c1", text: "My prompt has no personal information" }, { id: "c2", text: "My task is specific (says exactly what I want)" }],
    } },
    { type: "try_it", content: { title: "Teach an AI to recognise doodles", steps: ["Click the button to open Quick, Draw! in a new tab.", "Draw the 6 objects it asks for.", "Notice how the AI guesses while you draw!", "Come back here and mark it as done."], toolName: "Quick, Draw!", toolUrl: "https://quickdraw.withgoogle.com/", proof: "optional" } },
    { type: "checklist", content: { title: "Before you finish", items: [{ id: "k1", text: "I know what AI is" }, { id: "k2", text: "I know the 4 parts of a good prompt" }, { id: "k3", text: "I will never share personal info with AI" }] } },
    { type: "mcq", content: { question: "Which part of a prompt says HOW the answer should look?", multiple: false, options: [{ id: "a", text: "Role" }, { id: "b", text: "Task" }, { id: "c", text: "Context" }, { id: "d", text: "Format" }] },
      answerKey: { correct: ["d"], explanation: "Format describes the shape of the answer — list, table, poem…" }, settings: { points: 2 } },
    { type: "submission", content: { kind: "reflection", prompt: "In 3–4 sentences: where could AI help you in your studies, and what should you be careful about?", accepts: ["text"], rubric: [{ criterion: "Ideas", description: "Gives a realistic use of AI", maxPoints: 5 }, { criterion: "Responsibility", description: "Mentions checking facts or privacy", maxPoints: 5 }] } },
  ];
  addLesson("aiq", "aiq:l0", "aiq:m0", "aiq:les0", 0, "What is AI?", "Meet AI, see where you already use it, and test yourself.", lesson1, false);
  addLesson("aiq", "aiq:l0", "aiq:m0", "aiq:les1", 1, "Your first prompt", "Learn the Role-Task-Context-Format recipe and build your first prompt. (Level assessment)", lesson2, true);

  // ── Python Professional ──────────────────────────────────────────────────
  out.push(`insert into app.levels (id, program_id, position, name, slug, description) values
    (${q(id("py:l0"))}, ${q(id("py"))}, 0, 'Foundations', 'foundations', 'Variables, types and your first programs.') on conflict (id) do nothing;`);
  out.push(`insert into app.modules (id, level_id, position, title) values (${q(id("py:m0"))}, ${q(id("py:l0"))}, 0, 'Getting started') on conflict (id) do nothing;`);
  addLesson("py", "py:l0", "py:m0", "py:les0", 0, "Hello, Python", "Your first Python program.", [
    { type: "rich_text", content: { markdown: "Python is one of the most popular programming languages in the world.\n\n```python\nprint(\"Hello, Gadag!\")\n```\n\n`print()` shows text on the screen." } },
    { type: "callout", content: { variant: "tip", title: "Coming in Phase 4", markdown: "This lesson will include an in-browser code exercise (Pyodide) with auto-graded tests." } },
    { type: "key_terms", content: { title: "Key terms", terms: [{ term: "Function", definition: "A named block of code that does a job, like print().", link: "" }, { term: "String", definition: "Text inside quotes, like \"Hello\".", link: "" }] } },
    { type: "mcq", content: { question: "What does print(\"Hi\") do?", multiple: false, options: [{ id: "a", text: "Shows Hi on the screen" }, { id: "b", text: "Prints on paper" }, { id: "c", text: "Deletes Hi" }] }, answerKey: { correct: ["a"], explanation: "print() displays output on the screen." } },
    { type: "fill_blank", content: { text: "To show text in Python we use the [[1]] function." }, answerKey: { blanks: { "1": ["print", "print()"] } } },
  ], false);

  // ── Enrollments (trigger unlocks level 1) ────────────────────────────────
  for (const kid of ["aarav.k", "diya.s"]) {
    out.push(`insert into app.enrollments (id, user_id, program_id, status, source) values (${q(id("en:" + kid))}, ${q(id("u:" + kid))}, ${q(id("aiq"))}, 'active', 'bulk') on conflict do nothing;`);
  }
  out.push(`insert into app.enrollments (id, user_id, program_id, status, source) values (${q(id("en:learner"))}, ${q(id("u:learner"))}, ${q(id("py"))}, 'active', 'admin') on conflict do nothing;`);

  out.push(`insert into app.media_folders (id, name) values (${q(id("folder:aiq"))}, 'AI Explorer Quest'), (${q(id("folder:py"))}, 'Python Professional') on conflict do nothing;`);
  out.push("commit;");

  writeFileSync("supabase/seed.sql", out.join("\n") + "\n");
  console.log(`✓ wrote supabase/seed.sql (${out.length} statements). Demo password: ${DEMO_PASSWORD}`);
}

function addLesson(prog: string, level: string, mod: string, key: string, pos: number, title: string, summary: string, blocks: B[], assessment: boolean) {
  out.push(`insert into app.lessons (id, module_id, position, title, summary, is_assessment, status, estimated_minutes)
    values (${q(id(key))}, ${q(id(mod))}, ${pos}, ${q(title)}, ${q(summary)}, ${assessment}, 'draft', 15) on conflict (id) do nothing;`);
  const snapBlocks: any[] = [];
  blocks.forEach((b, i) => {
    const v = validateBlock(b.type, b.content, b.answerKey ?? {});
    if (!v.ok) throw new Error(`Seed block ${key}#${i} (${b.type}) invalid: ${v.error}`);
    const bid = id(`${key}:b${i}`);
    const settings = { points: 1, required: true, ...(b.settings ?? {}) };
    out.push(`insert into app.lesson_blocks (id, lesson_id, position, type, content, answer_key, settings)
      values (${q(bid)}, ${q(id(key))}, ${i}, ${q(b.type)}, ${j(v.content)}, ${j(v.answerKey)}, ${j(settings)}) on conflict (id) do nothing;`);
    let content: any = v.content;
    if (b.type === "sort") content = { ...content, items: shuffleAwayFrom(content.items, (v.answerKey as any).order, bid) };
    if (b.type === "match") content = { ...content, right: seededShuffle(content.right, bid) };
    snapBlocks.push({ id: bid, type: b.type, content, answer_key: v.answerKey, settings });
  });
  const snapshot = { title, summary, free_navigation: false, is_assessment: assessment, estimated_minutes: 15, blocks: snapBlocks };
  out.push(`insert into app.lesson_versions (id, lesson_id, program_id, version_no, snapshot, note, published_by)
    values (${q(id(key + ":v1"))}, ${q(id(key))}, ${q(id(prog))}, 1, ${j(snapshot)}, 'Initial seed', ${q(id("u:superadmin"))}) on conflict (id) do nothing;`);
  out.push(`update app.lessons set status = 'published', published_version_id = ${q(id(key + ":v1"))}, has_unpublished_changes = false where id = ${q(id(key))};`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
